# Generated by Django 5.1.6 on 2025-02-10 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quorum_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quorum_app.bill')),
            ],
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vote_type', models.IntegerField(choices=[(1, 'Yea'), (2, 'Nay')])),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quorum_app.person')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quorum_app.vote')),
            ],
        ),
    ]
